# Custom Language File for Launcher Customizer

[ejs.app]
title = "SocietyCraft Studios"

[ejs.landing]
mediaGitHubURL = "https://github.com/SocietyCraft/SocietyCraftLauncher"
mediaTwitterURL = "https://x.com/societycraft_"
mediaInstagramURL = "https://discord.com/invite/5DthbUAajx"
mediaYouTubeURL = "https://youtube.com/@societycraft1"
mediaDiscordURL = "https://discord.com/invite/5DthbUAajx"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur SocietyCraft"
welcomeDescription = "Notre mission à pour but de vous présenter un monde imaginer par notre équipe afin de vous montrer notre univers !"
welcomeDescCTA = "Vous n'êtes qu'a quelques clis de SocietyCraft !"
